sudo: required
language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
before_install:
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - go test ./...
  - go test -c -covermode=count -coverpkg=github.com/zaynjarvis/gotests,github.com/zaynjarvis/gotests/internal/input,github.com/zaynjarvis/gotests/internal/render,github.com/zaynjarvis/gotests/internal/goparser,github.com/zaynjarvis/gotests/internal/output,github.com/zaynjarvis/gotests/internal/models
  - ./gotests.test -test.coverprofile coverage.cov
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=coverage.cov
